### ISSUE TITLE
inv_sympd() error in cmf

### ISSUE THREAD

**Issue by matthias-studer** [vankesteren/cmfilter#5]
Hello, 

I am trying to use cmf, but I run into the following error:
-	error: inv_sympd(): matrix is singular or not positive definite
The R program itself then crash. 

I used the following script:
library(cmfilter)
load("data.RData")
res <- cmf(x, m, y, nCores=7)
x and y are numeric vector.
m is a data.frame with 118 potential mediators. 
There are  1051 observations.

Unfortunately, I am not allowed to share these data publicly. 

I have added my sessionInfo() below.
Hope this helps!
Matthias 

R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)

Matrix products: default

locale:
[1] LC_COLLATE=French_Switzerland.1252  LC_CTYPE=French_Switzerland.1252   
[3] LC_MONETARY=French_Switzerland.1252 LC_NUMERIC=C                       
[5] LC_TIME=French_Switzerland.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] cmfilter_0.9.3

loaded via a namespace (and not attached):
[1] compiler_4.1.1  Matrix_1.3-4    Rcpp_1.0.7      grid_4.1.1     
[5] lattice_0.20-45

**Comment by vankesteren** [comment]
I received the data from matthias (thanks!) and it turns out that he had a complex multicollinearity in the potential mediators m. This makes the covariance matrix of m singular. 

To investigate this, I ran the code `summary(lm(y ~ m))`, which showed some NAs in the coefficients. 

I inspected the dataset a bit further, and by looking at the nullspace of the covariance matrix of m you can see which variables are involved exactly:
`ns <- zapsmall(MASS::Null(crossprod(as.matrix(m))))`

In matthias' case, a linear combination of the variables 39-43 and 80-84 creates a vector of all zeros (`as.matrix(m)%*%ns`). This is multicollinearity.

When `cmfilter` selects these variables at the same time (which it is bound to do at some point!) it will crash, because it cannot invert the covariance matrix. Because the processing happens in parallel in C++ in the background the entire session crashes 😊

Potential solutions:
- The best solution would be for me to build in a small ridge regression penalty in the package. However, I don’t have time for this currently!
- You could take out the problematic variables if it makes sense to do so. I think it should be more stable.
- You could perturb your data very slightly, which is very similar to applying a ridge penalty. This would be my recommended option:
```r
m_ <- as.matrix(m) + matrix(rnorm(prod(dim(m)), sd = 0.000001), nrow(m))
summary(lm(y ~ m_)) 
```
